version: 2
project_name: argocd-extension-metrics

before:
  hooks:
    - go mod download
    - make build-ui

builds:
  - id: metrics-server
    main: ./cmd
    binary: metrics-server
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/victorbiga/argocd-extension-metrics/common.version={{ .Version }}
      - -X github.com/victorbiga/argocd-extension-metrics/common.buildDate={{ .Date }}
      - -extldflags="-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  # Create tarball for the extension
  - format: tar.gz
    id: extension-tar
    name_template: extension.tar
    meta: true
    files:
      - src: extensions/**/extension.tar
        strip_parent: true

checksum:
  name_template: 'extension_checksums.txt'
  algorithm: sha256

release:
  prerelease: auto
  draft: false
  header: |
    ## argocd-extension-metrics
    {{ .Date }}

    ### Artifacts

    - extension.tar.gz
    - extension_checksums.txt

  footer: |
    **Full Changelog**: https://github.com/victorbiga/argocd-extension-metrics/compare/{{ .PreviousTag }}...{{ .Tag }}
    <a href="https://argoproj.github.io/cd/"><img src="https://raw.githubusercontent.com/argoproj/argo-site/c42c87e68cea647eadc1564e9e264621442aa8cf/src/images/icon.png" width="25%" ></a>

changelog:
  use:
    github
  sort: asc
  abbrev: 0
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^.*?Bump(\([[:word:]]+\))?.+$'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
