name: test
on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    branches: [ main ]
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@5.3.0
        with:
          go-version: "1.21"
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@4.2.2
      - name: Restore Go build cache
        uses: actions/cache@4.2.0
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}
      - name: Get dependencies
        run: go mod download
      - name: build
        run: make
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOPATH: /home/runner/go
    steps:
      - uses: actions/checkout@4.4.1
      - name: Setup Golang
        uses: actions/setup-go@5.3.0
        with:
          go-version: "1.21"
      - name: Restore Go build cache
        uses: actions/cache@4.2.0
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}
      - run: make test
