name: release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'argoproj-labs/argocd-extension-metrics'
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@5a083d0e9a84784eb32078397cf5459adecb4c40 # pin@v4
        with:
          go-version: 1.21

      - name: Docker Login in quay.io
        uses: docker/login-action@3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5fdedb94abba051217030cc86d4523cf3f02243d # pin@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
