name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required to create or update releases
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'victorbiga/argocd-extension-metrics'
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.21

      - name: Docker Login in quay.io
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DCOKER_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_BUILDX: "true"
          DOCKER_BUILDKIT: 1
