name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required to create or update releases
  id-token: write

defaults:
  run:
    shell: bash
   
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'victorbiga/argocd-extension-metrics'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DCOKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag victorbiga/argocd-extension-metrics:${{ github.ref_name }} \
            --tag victorbiga/argocd-extension-metrics:latest \
            --file release.Dockerfile \
            --push .
